### ISSUE TITLE
implement UI and code for sights and icons

### ISSUE THREAD

**Issue by NDDC-Repository** [NDDC-Repository/NddcWebsiteCMSApp#18]

**Comment by Orchiid** [comment]
SqlException: Invalid object name 'SightsAndIcons'.

**Comment by Orchiid** [comment]
Hi Uncle Daggy I'm still getting this error on add sights
SqlException: String or binary data would be truncated. The statement has been terminated.

Details:
WebsiteCMSLibrary.Databases.SqlDataAccess.SaveData<T>(string sqlStatement, T parameters, string connectionStringName, bool isStoredProcedure) in SqlDataAccess.cs

+ connection.Execute(sqlStatement, parameters, commandType: commandType);
WebsiteCMSLibrary.Data.HomePage.SightsAndIcon.SQLSightsAndIcons.AddSightsAndIcons(MySightsAndIconsModel sight) in SQLSightsAndIcons.cs

+ db.SaveData("Insert Into SightsAndIcons (Title, Summary, ImageUrl, Details, DateAdded, AddedBy) values(@Title, @Summary, @ImageUrl, @Details, @DateAdded, @AddedBy)", new { Title = sight.Title, Summary = sight.Summary, ImageUrl = sight.ImageUrl, Details = sight.Details, DateAdded = dateAdded, AddedBy = addedBy }, connectionStringName, false);
NddcWebsiteCMS.Pages.Media.Sights.AddSightsModel.OnPost() in AddSights.cshtml.cs

+ sightsDb.AddSightsAndIcons(Sights);
