### ISSUE TITLE
SqlException: Invalid object name 'SightsAndIcons'.

### ISSUE THREAD

**Issue by Orchiid** [NDDC-Repository/NddcWebsiteCMSApp#25]
Errors Shown here:

SqlDataAccess.cs
+38
List<T> rows = connection.Query<T>(sqlStatement, parameters, commandType: commandType).ToList();
WebsiteCMSLibrary.Data.HomePage.SightsAndIcon.SQLSightsAndIcons.AllSightsAndIcons() in SQLSightsAndIcons.cs
+28
return db.LoadData<MySightsAndIconsModel, dynamic>("select ROW_NUMBER() OVER (ORDER BY Id DESC) As SrNo, Id, Title, Summary, ImageUrl, Details, DateAdded from SightsAndIcons Order By Id DESC", new { }, connectionStringName, false).ToList();

NddcWebsiteCMS.Pages.Media.Sights.AllSightsModel.OnGet()

**Comment by NDDC-Repository** [comment]
@Orchiid please check if you have the table for SightsAndIcons in your database. if you dont have it use the this

USE [NDDC-Website]
GO

/****** Object:  Table [dbo].[SightsAndIcons]    Script Date: 24/02/2024 07:31:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SightsAndIcons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](350) NULL,
	[Summary] [nvarchar](500) NULL,
	[ImageUrl] [nvarchar](150) NULL,
	[Details] [text] NULL,
	[DateAdded] [datetime] NULL,
	[AddedBy] [nvarchar](100) NULL,
 CONSTRAINT [PK_SightsAndIcons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

**Comment by Orchiid** [comment]
Ok I did that. But I'm getting this error: SqlException: Must declare the scalar variable "@Title".
